import { Badge } from '@/components/ui/badge';
import { Card, CardContent } from '@/components/ui/card';

const steps = [
  {
    id: 1,
    step: 'Step 1',
    title: 'Share your aspirations',
    description:
      'Tell our AI about your career goals and interests. It analyzes your background to suggest the most impactful skills to develop.'
  },
  {
    id: 2,
    step: 'Step 2',
    title: 'Get your AI-generated roadmap',
    description:
      'Our AI creates a personalized learning plan with curated resources, realistic timelines, and weekly milestones tailored to your schedule.'
  },
  {
    id: 3,
    step: 'Step 3',
    title: 'Practice with AI-crafted exercises',
    description: 'Apply what you learn through real-world scenarios generated by AI based on your progress and industry context.'
  },
  {
    id: 4,
    step: 'Step 4',
    title: 'Reflect and adapt',
    description: "Share your insights and our AI adjusts your path forward, ensuring you're always learning at the optimal pace."
  },
  {
    id: 5,
    step: 'Step 5',
    title: 'Celebrate achievements',
    description: 'Earn rewards and identify breakthroughs on your path to mastery.'
  }
];

export default function HowItWorksSection() {
  return (
    <section id="how-it-works" className="relative bg-muted py-20 md:py-28">
      {/* Blurred gradient circle background */}
      <div
        className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-225 h-225 rounded-full opacity-60 blur-[120px]"
        style={{
          background: 'radial-gradient(circle, #FFA500 0%, #FF6B6B 40%, transparent 70%)'
        }}
        aria-hidden="true"
      />
      <div className="container mx-auto px-4 relative z-10">
        {/* Section Header */}
        <div className="text-center mb-16">
          <h2 className="text-4xl font-extrabold text-foreground sm:text-5xl">From Goal to Done</h2>
          <p className="mt-4 text-lg text-muted-foreground max-w-2xl mx-auto">
            A clear, step-by-step path to help you cross the finish line.
          </p>
        </div>
        {/* Steps in Single Card */}
        <div className="max-w-2xl mx-auto">
          <Card className="border-2 border-muted">
            <CardContent className="p-0">
              {steps.map((item) => (
                <div key={item.id} className={`flex flex-col sm:flex-row gap-4 p-6`}>
                  <div className="shrink-0">
                    <Badge variant="outline" className="text-base font-bold px-4 py-2 border-0 text-accent bg-accent/10">
                      {item.step}
                    </Badge>
                  </div>
                  <div className="flex-1">
                    <h3 className="text-2xl font-bold text-foreground mb-2">{item.title}</h3>
                    <p className="text-base text-muted-foreground leading-relaxed">{item.description}</p>
                  </div>
                </div>
              ))}
            </CardContent>
          </Card>
        </div>
      </div>
    </section>
  );
}
