import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";

const steps = [
  {
    id: 1,
    step: "Step 1",
    title: "Share your aspirations",
    description: "Tell our AI about your career goals and interests. It analyzes your background to suggest the most impactful skills to develop."
  },
  {
    id: 2,
    step: "Step 2",
    title: "Get your AI-generated roadmap",
    description: "Our AI creates a personalized learning plan with curated resources, realistic timelines, and weekly milestones tailored to your schedule."
  },
  {
    id: 3,
    step: "Step 3",
    title: "Practice with AI-crafted exercises",
    description: "Apply what you learn through real-world scenarios generated by AI based on your progress and industry context."
  },
  {
    id: 4,
    step: "Step 4",
    title: "Reflect and adapt",
    description: "Share your insights and our AI adjusts your path forward, ensuring you're always learning at the optimal pace."
  },
  {
    id: 5,
    step: "Step 5",
    title: "Celebrate AI-recognized achievements",
    description: "Earn rewards as our AI tracks your growth, identifies breakthroughs, and celebrates milestones you might have missed."
  }
];

export default function HowItWorksSection() {
  return (
    <section id="how-it-works" className="bg-muted py-20 md:py-28">
      <div className="container mx-auto px-4">
        {/* Section Header */}
        <div className="text-center mb-16">
          <h2 className="text-4xl font-extrabold text-foreground sm:text-5xl">
            How our AI guides you
          </h2>
          <p className="mt-4 text-lg text-muted-foreground max-w-2xl mx-auto">
            A personalized, AI-driven process that adapts to your unique learning style and goals.
          </p>
        </div>

        {/* Steps in Single Card */}
        <div className="max-w-3xl mx-auto">
          <Card className="border-2 border-border">
            <CardContent className="p-0">
              {steps.map((item, index) => (
                <div 
                  key={item.id}
                  className={`flex flex-col sm:flex-row gap-4 p-6 ${
                    index !== steps.length - 1 ? 'border-b-2 border-muted' : ''
                  }`}
                >
                  <div className="flex-shrink-0">
                    <Badge 
                      variant="outline" 
                      className="text-base font-bold px-4 py-2 border-0 text-accent bg-accent/10"
                    >
                      {item.step}
                    </Badge>
                  </div>
                  <div className="flex-1">
                    <h3 className="text-2xl font-bold text-foreground mb-2">
                      {item.title}
                    </h3>
                    <p className="text-base text-muted-foreground leading-relaxed">
                      {item.description}
                    </p>
                  </div>
                </div>
              ))}
            </CardContent>
          </Card>
        </div>
      </div>
    </section>
  );
}